# Generated by Django 3.1.6 on 2021-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_threads', '0003_auto_20210402_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
