# Generated by Django 3.1.6 on 2021-04-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_threads', '0006_thread_sticky_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
