# Generated by Django 3.1.6 on 2021-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_threads', '0007_auto_20210402_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
