# Generated by Django 3.2 on 2021-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_threads', '0008_auto_20210424_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread_Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=80)),
                ('comment_content', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
