# Generated by Django 3.2 on 2021-04-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_threads', '0009_auto_20210426_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread_Comments',
            new_name='Thread_Comment',
        ),
    ]
