# Generated by Django 3.2 on 2021-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_threads', '0014_alter_thread_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='live_thread_content',
            field=models.TextField(blank=True),
        ),
    ]
