# Generated by Django 3.2 on 2021-05-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vote_amount',
            field=models.IntegerField(default=100),
        ),
    ]
