# Generated by Django 3.2 on 2021-05-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile_vote_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='common_user_tags',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
