# Generated by Django 3.2 on 2021-05-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_profile_common_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_tag_collection',
            field=models.TextField(default='False'),
        ),
    ]
