# Generated by Django 3.2 on 2021-05-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_profile_user_tag_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='common_user_tags',
            field=models.CharField(default=['none'], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_tag_collection',
            field=models.TextField(default=['none']),
        ),
    ]
