# Generated by Django 3.2 on 2021-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210507_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='common_user_tags',
            field=models.CharField(default='["none"]', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_tag_collection',
            field=models.TextField(default='["none"]'),
        ),
    ]
