# Generated by Django 3.2 on 2021-05-17 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210513_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_online',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 15, 48, 34, 210286)),
        ),
    ]
