# Generated by Django 3.2 on 2021-05-17 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_profile_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_online',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
